export type Permission = `${string}:${string}`;

export const PERMISSIONS = [
  "organization:invite_user",
  "organization:remove_user",
  "organization:list_users",
  "organization:update_user_role",
  "organization:create_role",
  "organization:update_role",
  "organization:delete_role",
  "organization:assign_role",
  "organization:list_roles",
  "organization:update_settings",
  "organization:read_settings",
  "organization:create_team",
  "organization:update_team",
  "organization:delete_team",
  "organization:add_user_to_team",
  "organization:remove_user_from_team",
  "organization:list_teams",
  "organization:create_project",
  "organization:update_project",
  "organization:delete_project",
  "organization:read_project",
  "organization:list_projects",
  "organization:invite_admin",
  "organization:revoke_admin",
  "organization:manage_billing",
] as const;
